"""add patient mrn

Revision ID: 07da450003bc
Revises: ad86ad600d53
Create Date: 2026-07-16 22:37:36.036881

"""
from alembic import op
import sqlalchemy as sa


revision = '07da450003bc'
down_revision = 'ad86ad600d53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('mrn', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_column('patients', 'mrn')
    # ### end Alembic commands ###
