"""initial schema

Revision ID: ad86ad600d53
Revises: 
Create Date: 2026-07-16 18:21:01.389769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ad86ad600d53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tool_calls_used', sa.Integer(), nullable=False),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_runs_patient_id'), 'investigation_runs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_investigation_runs_run_id'), 'investigation_runs', ['run_id'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.create_table('allergies',
    sa.Column('substance', sa.String(length=128), nullable=False),
    sa.Column('reaction', sa.String(length=256), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_patient_id'), 'allergies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_allergies_source_resource_id'), 'allergies', ['source_resource_id'], unique=True)
    op.create_table('care_plans',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_plans_patient_id'), 'care_plans', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_plans_source_resource_id'), 'care_plans', ['source_resource_id'], unique=True)
    op.create_index(op.f('ix_care_plans_topic'), 'care_plans', ['topic'], unique=False)
    op.create_table('conditions',
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('display', sa.String(length=256), nullable=False),
    sa.Column('clinical_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_patient_id'), 'conditions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_conditions_source_resource_id'), 'conditions', ['source_resource_id'], unique=True)
    op.create_table('deferrals',
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('deferred_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_note_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deferrals_patient_id'), 'deferrals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_deferrals_source_resource_id'), 'deferrals', ['source_resource_id'], unique=True)
    op.create_index(op.f('ix_deferrals_topic'), 'deferrals', ['topic'], unique=False)
    op.create_table('encounters',
    sa.Column('encounter_type', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_source_resource_id'), 'encounters', ['source_resource_id'], unique=True)
    op.create_table('investigation_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['investigation_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_steps_run_id'), 'investigation_steps', ['run_id'], unique=False)
    op.create_table('medications',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dose', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=32), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medications_source_resource_id'), 'medications', ['source_resource_id'], unique=True)
    op.create_table('metric_snapshots',
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('display', sa.String(length=128), nullable=False),
    sa.Column('latest_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('latest_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('slope_per_month', sa.Float(), nullable=True),
    sa.Column('n_points', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_metric_code'), 'metric_snapshots', ['metric_code'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_patient_id'), 'metric_snapshots', ['patient_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_source_resource_id'), 'metric_snapshots', ['source_resource_id'], unique=True)
    op.create_table('notes',
    sa.Column('note_type', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_patient_id'), 'notes', ['patient_id'], unique=False)
    op.create_index('ix_notes_search_vector', 'notes', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_notes_source_resource_id'), 'notes', ['source_resource_id'], unique=True)
    op.create_table('observations',
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('display', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('value_text', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_metric_code'), 'observations', ['metric_code'], unique=False)
    op.create_index(op.f('ix_observations_patient_id'), 'observations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_observations_source_resource_id'), 'observations', ['source_resource_id'], unique=True)
    op.create_table('orders',
    sa.Column('order_type', sa.String(length=64), nullable=False),
    sa.Column('display', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_patient_id'), 'orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_orders_source_resource_id'), 'orders', ['source_resource_id'], unique=True)
    op.create_table('procedures',
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('display', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('clinical_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_resource_id', sa.String(length=128), nullable=False),
    sa.Column('raw_source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_patient_id'), 'procedures', ['patient_id'], unique=False)
    op.create_index(op.f('ix_procedures_source_resource_id'), 'procedures', ['source_resource_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procedures_source_resource_id'), table_name='procedures')
    op.drop_index(op.f('ix_procedures_patient_id'), table_name='procedures')
    op.drop_table('procedures')
    op.drop_index(op.f('ix_orders_source_resource_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_patient_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_observations_source_resource_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_patient_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_metric_code'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_notes_source_resource_id'), table_name='notes')
    op.drop_index('ix_notes_search_vector', table_name='notes', postgresql_using='gin')
    op.drop_index(op.f('ix_notes_patient_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_metric_snapshots_source_resource_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_patient_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_metric_code'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_medications_source_resource_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_investigation_steps_run_id'), table_name='investigation_steps')
    op.drop_table('investigation_steps')
    op.drop_index(op.f('ix_encounters_source_resource_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_deferrals_topic'), table_name='deferrals')
    op.drop_index(op.f('ix_deferrals_source_resource_id'), table_name='deferrals')
    op.drop_index(op.f('ix_deferrals_patient_id'), table_name='deferrals')
    op.drop_table('deferrals')
    op.drop_index(op.f('ix_conditions_source_resource_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_patient_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_care_plans_topic'), table_name='care_plans')
    op.drop_index(op.f('ix_care_plans_source_resource_id'), table_name='care_plans')
    op.drop_index(op.f('ix_care_plans_patient_id'), table_name='care_plans')
    op.drop_table('care_plans')
    op.drop_index(op.f('ix_allergies_source_resource_id'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_patient_id'), table_name='allergies')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_investigation_runs_run_id'), table_name='investigation_runs')
    op.drop_index(op.f('ix_investigation_runs_patient_id'), table_name='investigation_runs')
    op.drop_table('investigation_runs')
    # ### end Alembic commands ###
