"""annotation events

Revision ID: ce549093538a
Revises: 07da450003bc
Create Date: 2026-07-17 11:34:32.816956

"""
from alembic import op
import sqlalchemy as sa


revision = 'ce549093538a'
down_revision = '07da450003bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('quote', sa.String(length=500), nullable=False),
    sa.Column('quote_hash', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('note_hash', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_events_patient_id'), 'annotation_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_annotation_events_quote_hash'), 'annotation_events', ['quote_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_events_quote_hash'), table_name='annotation_events')
    op.drop_index(op.f('ix_annotation_events_patient_id'), table_name='annotation_events')
    op.drop_table('annotation_events')
    # ### end Alembic commands ###
